#!/bin/bash

# shellcheck disable=2001  ## Complaining about use of sed istead of bash search & replace.
# shellcheck disable=2002  ## Useless use of cat. This works well though and I don't want to break it for the sake of syntax purity.
# shellcheck disable=2004  ## Inappropriate complaining of "$/${} is unnecessary on arithmetic variables."
# shellcheck disable=2034  ## Unused variables.
# shellcheck disable=2086
# shellcheck disable=2119  ## Disable confusing and inapplicable warning about function's $1 meaning script's $1.
# shellcheck disable=2120  ## OK with declaring variables that accept arguments, without calling with arguments (this is 'overloading').
# shellcheck disable=2143  ## Used grep -q instead of echo | grep
# shellcheck disable=2155  ## Disable check to 'Declare and assign separately to avoid masking return values'.
# shellcheck disable=2162
# shellcheck disable=2181
# shellcheck disable=2317  ## Can't reach

##	Purpose: See fPrint_AboutAndSyntax() and fPrint_Help().
##	History:
##		- 20230830 JC: Created from x9convertbase1 as template.
##		- 20230924 JC: Finished.
##		- 20260226 JC: Don't try xclip if not installed, and don't error if it doesn't work.

#notify-send "Test from '${0}'"

## Constants (not actually read-only; that errors out on re-entry).
declare -i    doQuietly=0; [[ ${X9MUID1_QUIET} -eq 1 ]] && doQuietly=1
declare       thisVersion="0.9.0"
declare       copyrightYear="2023"
declare       author="Jim Collier"


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fConfig(){ :;

	## Defaults
	default_outBase="62"
	default_outFormat="%d" #............: A string with possible variables: %d[ate], %h[ost], %f[QDN], %m[AC], %u[UID], %r[andom]
	default_dtAlgo=1
	default_precision_DateTime=0 #...: 0, -1, 1
	dofault_doLCaseIfAppropriate=1
	default_doHash_UserName=1
	default_doHash_HostName=1
	default_doHash_FQDN=1
	default_keepOnlyRighmostHashChars_UserName=5
	default_keepOnlyRighmostHashChars_HostName=5
	default_keepOnlyRighmostHashChars_FQDN=8
	default_randomCharCount=4
	default_doClipOut=0

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fPrint_AboutAndSyntax(){
	((doQuietly)) && return
	fEcho_Clean ""
	#  X-------------------------------------------------------------------------------X
	cat <<- EOF_ng50ne2
		Multiversal Unique ID. Can be way more unique than UUID, but by default, is
		less unique - but also much shorter, human-readable/sortable, while still
		privacy-protecting. By default, it converts the current time using --dtalgo 1
		below, transformed to a base ${default_outBase} string.

		Syntax: ${meName} [optional args]
		  Optional arguments:

		    --format <FORMAT> (default if not specified: "%d")
		      Any string that may contain the following the following variables:
		        %datetime ...: Date/time (format according to --dtalgo)
		        %username ...: Username, by default cryptographically hashed
		        %hostname ...: Hostname, by default cryptographically hashed
		        %fqdn .......: Fully-qualified host and domain name
		        %mac ........: MAC address of the first network adapter with a gateway
		        %guid .......: UUID v4 (%uuid also acceptable)
		        %random .....: Randomly-generated number
		      You can include any other text, eg delimiters. You may also use common
		      abbreviations for each (eg "%dt" instead of "%datetime"), or just the
		      first letter in unambiguous cases.

		    --base <base>: The output base (${default_outBase} if not specified), one of:
		      Actual standards:
		         10 ....: aka Decimal [default] ...... 0-9
		         16 ....: aka Hexedecimal ............ 0-9, A-F
		         32[r]..: RFC 4648 ................... A-Z, 2-7
		         32h ...: RFC 4648 §7, 'Base32Hex' ... 0-9, A-V
		         32w ...: Wordsafe Base32 ............ 2-9, CFGHJMPQRVWX, cfghjmpqrvwx
		         36 ....: Just alphanum .............. 0-9, A-Z
		         62 ....: All alphanum ............... 0-9, A-Z, a-z
		         64[r]..: RFC 4648 ................... 0-9, A-Z, a-z, +, /
		         64u ...: RFC 4648 §5; URL-safe ...... 0-9, A-Z, a-z, -, _
		      De-facto standards:
		         26 ....: One-case alphabetic ........ A-Z
		         32c ...: Crockford's Base32 ......... 0-9, A-Z no I, L, O, U
		         52 ....: Both-case alphabetic ....... A-Z, a-z
		      Very slightly custom:
		         64j1u..: Slight alternate to 64u but unicode instead of "-_"
		      Fully custom (URL-safe, filesystem-safe, word-safe, programmer-friendly):
		         48j1...: 0-9, cfghjmpqrvwx, and lots of unicode symbols
		         64j1uw.: 0-9, Like 48j1 but with upper-case too
		        128[j1].: Like 64j1u but with way more unicode symbols
		        256[j1].: 0-9, A-Z, a-z, and lots of unicode chars
		      Recommendations:
		        ▸ Max long-term standardization .....: 26, 36, 52, 62
		        ▸ Balance standard w/ word-safety ...: 32c, 32w
		        ▸ Standard, URL-safe, filesystem-safe: 26, 32*, 36, 52, 62, 64u
		        ▸ URL & FS-safe, programmer-friendly : 26, 32*, 36, 52, 62, *j1*
		        ▸ Max word-safety ...................: 32w, *j1* except 64j1u

		    --dtalgo <TYPE> (default if not specified: 1)
		      1: Converts current UTC unix seconds since 1970-01-01 00:00:00, to a
		         shorter serial string. Pros: ▸Tied for shortest. Cons: ▸While results
		         are self-comparable, the least human-readable among these. ▸Won't
		         serialize dates prior to 1970 (to avoid extra symbols for negative).
		      2: Treats current UTC time in YYYYMMDDHHmmSS as one big integer, then
		         converts it to the specified base. Pros: ▸Simplest. Cons:
		         ▸Least efficient. ▸While results are self-comparable, the second-least
		         human-readable.
		      3: Treats [YYYY][MM][DD][HH][mm][SS] as separate fields, base-converts
		         each separately, then rejoins into one string. Pros: ▸Fixed-position
		         fields. ▸Can be human-readable. ▸Longest option for bases <62 (eg 32).
		      4: Like #2 for [YYYY][MM][DD], but each day ([HH][mm][SS]) is divided up
		         evenly to maximize the granularity of the entire specified numeric
		         base. Pros: ▸Shortest. ▸Fixed-position & human-comparable to the day.
		         ▸With practice, the short time-of-day field is arguably even useful.

		    --dtprecision <-1|0|1> The millenium and/or second precision for date/time:
		      ▸  0 : Default; eg millenium & 1 second depending on --dtalgo and --base
		      ▸ -1 : Less precise, OK to year 2999, ~minute-level precision
		      ▸  1 : More precise, millisecond depending on --dtalgo and --base

		    --random-char-count: If using %r, how many characters
		    --lcase <0|1>......: Convert to lcase for single-case bases (default: ${dofault_doLCaseIfAppropriate})
		    --clipout <0|1>....: Copy output to clipboard (default: ${default_doClipOut})
		    --help ............: Show extra information on options and bases.

		    --hash-[username|hostname|fqdn] <0|1>:
		      If %h|%f are in --format, sha256 the hostname or FQDN

		    --keep-only-righmost-hash-chars-[username|hostname|fqdn] <NUM>
		      If --hash-[username|hostname|fqdn] is in effect, keep only the righntmost
		      NUM chars of the resulting hash

		    --dtoverride <"date/time string recognizable by 'date' command">
		      Instead of using the current UTC date/time, use the specified date/time.
		      Be sure to provide enough precision for for other arguments, e.g.
		      "2025-06-21 15:45:31.951" if also passing '--dtprecision 1'.
	EOF_ng50ne2
	#  X-------------------------------------------------------------------------------X
	fEcho_Force ""
}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fPrint_Help(){
	((doQuietly)) && return
	fEcho_Clean ""
	#  X-------------------------------------------------------------------------------X
	cat <<- EOF_ng50mzv
		Examples of --dtalgo, for a UTC date of 2025-06-21 at 3:45:31 PM:

		--dtalgo     base10    base62    Res²  #³  Till⁴  prec -1⁵  #  Res   Till
		  1      1750520731    1uT0PL     1s   6   3769     1yPwr   5   1m   3711
		  2  20250621154531  5kWSUchH     1s   8  21834    RM656b   6   1m   2056
		  3  20250621154531   Wf6LFjV     1s   7   3843     P6LFj   5   1m   2061
		  4   2025062106566   Wf6L1hu    >1s   7   3843     P6Lei   5  22s   2061

		--dtalgo              base32c¹   Res   #   Till   prec -1   #  Res   Till
		  1                   1m5dmwv     1m   7   3058     vtbhh   5   1m   2033
		  2                 jdbvh9573     1m   9   3519   2ap3g6s   7   1m   2343
		  3                1z96nf1d0z     1m  10  32768    s6nf1d   6   1m   2031
		  4                  1z96nn0c   2.6s   8  32768   1z96nn0   7  84s  32768

		Footnotes:

		  ¹: Listed here is Crockford base32 variant with --lcase.
		  ²: Time resolution; the number of seconds per unique rightmost character.
		  ³: Character count in the output.
		  ⁴: The year that the character count will necessarily increase by 1.
		  ⁵: If '--dtprecision -1' flag used, eg no millenium and/or seconds.

		Notes:

		  ▸ For any given use-case, you should never mix type, base, and/or precision,
		    or the very purpose for using this tool could be obviated and you'd wind up
		    hating life at best, or with data collisions and/or loss data at worst. If
		    you might do so, you should prepend the type, base and precision to the
		    result (which is longer than just "YYYYMMDDHHMMSS" in decimal form), or at
		    least note them in another field.

		  ▸ The following bases are resistant to accidentally spelling out naughty
		    words: 32c[rockford], and especially 32w, 48j1, 64j1uw, and 128j1.

		  ▸ All --dtalgos and bases are human-readable/comparable. But not even RFC
		    standard bases >36 will machine-sort properly with common sort regimes, eg
		    LC_COLLATE=C.UTF-8, etc.

		Recommendations for various --dtalgo goals:

		  ▸ Human parseability and brevity ................: --dtalgo 4 --base 62
		  ▸ Absolute brevity and URL/file/programmer safety: --dtalgo 1 --base 256j1
		  ▸ Maximum readability with bad handwriting ......:            --base 32c
		  ▸ Minimal odds of accidental bad words ..........:            --base 32w
		  ▸ Human parseability of time fields .............: --dtalgo 3
	EOF_ng50mzv
	#  X-------------------------------------------------------------------------------X
	fEcho_Force ""
}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fPrint_Copyright(){
	((doQuietly)) && return
	fEcho_Clean ""
	cat <<- EOF_q9tan
		${meName} version ${thisVersion}
		Copyright (c) ${copyrightYear} ${author}.
		License GPLv3+: GNU GPL version 3 or later, full text at:
		    https://www.gnu.org/licenses/gpl-3.0.en.html
		There is no warranty, to the extent permitted by law.
	EOF_q9tan
	fEcho_Force ""
}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fMain(){

	## Pre-validation
	_fMustBeInPath basename
	_fMustBeInPath x9convertbase1

	## Make template constants immutible
	local -r  meName="${meName}"

	## Token constants (these should be as weird as possible and least likely to be used either in user formatting, or any numeric base character set)
	## Depending on display font these may look the same, but are (or should be) each unique unicode characters.
	local -r token_DateTime="🟥"
	local -r token_UserName="🟧"
	local -r token_HostName="🟨"
	local -r token_FQDN="🟩"
	local -r token_MAC="🟦"
	local -r token_UUID="🟪"
	local -r token_Random="🟫"

	## Config; 1] Define placeholder variables; 2] Call fConfig() to set them; 3] Freeze them as read-only.
	local    default_outBase=""
	local    default_outFormat=""
	local -i default_dtAlgo=0
	local -i default_precision_DateTime=0
	local -i dofault_doLCaseIfAppropriate=0
	local -i default_doHash_UserName=0
	local -i default_doHash_HostName=0
	local -i default_doHash_FQDN=0
	local -i default_keepOnlyRighmostHashChars_UserName=0
	local -i default_keepOnlyRighmostHashChars_HostName=0
	local -i default_keepOnlyRighmostHashChars_FQDN=0
	local -i default_randomCharCount=0
	local -i default_doClipOut=0
	local    format_DateTime_ToSecond=""
	fConfig
	local -r  default_outBase="${default_outBase}"
	local -r  default_outFormat="${default_outFormat}"
	local -ir default_dtAlgo=$default_dtAlgo
	local -ir default_precision_DateTime=$default_precision_DateTime
	local -ir dofault_doLCaseIfAppropriate=$dofault_doLCaseIfAppropriate
	local -ir default_doHash_UserName=$default_doHash_UserName
	local -ir default_doHash_HostName=$default_doHash_HostName
	local -ir default_doHash_FQDN=$default_doHash_FQDN
	local -ir default_keepOnlyRighmostHashChars_UserName=$default_keepOnlyRighmostHashChars_UserName
	local -ir default_keepOnlyRighmostHashChars_HostName=$default_keepOnlyRighmostHashChars_HostName
	local -ir default_keepOnlyRighmostHashChars_FQDN=$default_keepOnlyRighmostHashChars_FQDN
	local -ir default_randomCharCount=$default_randomCharCount
	local -ir default_doClipOut=$default_doClipOut
	local    format_DateTime_ToSecond="${format_DateTime_ToSecond}"

	## Args; 1] Define placeholder variables; 2] Call fInit() [which then calls fValidate()] to set them; 3] Freeze them read-only.
	local -a allArgs=()
	local    outFormat=""
	local    dtOverride=""
	local    outBase=""
	local -i outBaseInt=0
	local -i dtAlgo=0
	local -i doAlgo_DateTime=0
	local -i doAlgo_UserName=0
	local -i doAlgo_HostName=0
	local -i doAlgo_FQDN=0
	local -i doAlgo_MAC=0
	local -i doAlgo_UUID=0
	local -i doAlgo_Random=0
	local -i precision_DateTime=0
	local -i randomCharCount=0
	local -i doLCaseIfAppropriate=0
	local -i doHash_UserName=0
	local -i doHash_HostName=0
	local -i doHash_FQDN=0
	local -i keepOnlyRighmostHashChars_UserName=0
	local -i keepOnlyRighmostHashChars_HostName=0
	local -i keepOnlyRighmostHashChars_FQDN=0
	local -i doClipOut=$default_doClipOut
	fInit "${@}"
	local -ra allArgs=("${allArgs[@]}")
	local -r  outFormat="${outFormat}"
	local -r  dtOverride="${dtOverride}"
	local -r  outBase="${outBase}"
	local -ir outBaseInt=$outBaseInt
	local -ir dtAlgo=$dtAlgo
	local -ir doAlgo_DateTime=$doAlgo_DateTime
	local -ir doAlgo_UserName=$doAlgo_UserName
	local -ir doAlgo_HostName=$doAlgo_HostName
	local -ir doAlgo_FQDN=$doAlgo_FQDN
	local -ir doAlgo_MAC=$doAlgo_MAC
	local -ir doAlgo_UUID=$doAlgo_UUID
	local -ir doAlgo_Random=$doAlgo_Random
	local -ir precision_DateTime=$precision_DateTime
	local -ir randomCharCount=$randomCharCount
	local -ir doLCaseIfAppropriate=$doLCaseIfAppropriate
	local -ir doHash_UserName=$doHash_UserName
	local -ir doHash_HostName=$doHash_HostName
	local -ir doHash_FQDN=$doHash_FQDN
	local -ir keepOnlyRighmostHashChars_UserName=$keepOnlyRighmostHashChars_UserName
	local -ir keepOnlyRighmostHashChars_HostName=$keepOnlyRighmostHashChars_HostName
	local -ir keepOnlyRighmostHashChars_FQDN=$keepOnlyRighmostHashChars_FQDN
	local -ir doClipOut=$doClipOut

	##Debug
	#echo -e "allArgs = '${allArgs[*]}'"
	#echo "Arg count = ${#allArgs[@]}"
	#fEchoVarAndVal dtOverride
	#fEchoVarAndVal outBase
	#fEchoVarAndVal outFormat
	#fEchoVarAndVal dtAlgo
	#fEchoVarAndVal doAlgo_DateTime
	#fEchoVarAndVal doAlgo_UserName
	#fEchoVarAndVal doAlgo_HostName
	#fEchoVarAndVal doAlgo_FQDN
	#fEchoVarAndVal doAlgo_MAC
	#fEchoVarAndVal doAlgo_UUID
	#fEchoVarAndVal doAlgo_Random
	#fEchoVarAndVal precision_DateTime
	#fEchoVarAndVal randomCharCount
	#fEchoVarAndVal doLCaseIfAppropriate
	#fEchoVarAndVal doHash_UserName
	#fEchoVarAndVal doHash_HostName
	#fEchoVarAndVal doHash_FQDN
	#fEchoVarAndVal keepOnlyRighmostHashChars_UserName
	#fEchoVarAndVal keepOnlyRighmostHashChars_HostName
	#fEchoVarAndVal keepOnlyRighmostHashChars_FQDN
	#fEchoVarAndVal doClipOut
	#fEcho
	#exit

	##
	## Make it so
	##

	local -i tmpMatchIndex=0
	local preOutputStr=""

	## Lower case?
	local extCliFlags=""
	((doLCaseIfAppropriate)) && extCliFlags="${extCliFlags} --lcase"

	## Build output string
	local outputStr="${outFormat}"

	## Username
	if ((doAlgo_UserName)); then
		preOutputStr=""
		preOutputStr="${USER}"
		[[ -z "${preOutputStr}" ]] && preOutputStr="${USERNAME}"
		if [[ -n "${preOutputStr}" ]]; then
			if ((doHash_UserName)); then
				## Cryptographic hash
				preOutputStr="$(echo "${preOutputStr}" | sha256sum | grep -iPo "[0123456789abcdef]+")"  ## existence of sha256sum is already checked in fInit().
				[[ -n "${preOutputStr}" ]] && preOutputStr="${preOutputStr^^}"
				[[ -n "${preOutputStr}" ]] && preOutputStr="$(x9convertbase1 $extCliFlags --ibase 16 ${preOutputStr} $outBase)"
				[[ -n "${preOutputStr}" ]] && [[ $keepOnlyRighmostHashChars_UserName -gt 0 ]] && [[ $keepOnlyRighmostHashChars_UserName -lt ${#preOutputStr} ]] && preOutputStr="${preOutputStr: -$keepOnlyRighmostHashChars_UserName}"
			else :;
				## Do numeric conversion if and when x9convertbase1 supports --ibase of '38username'.
				## For now just leave username unaltered.
				true
			fi
		fi
		[[ -z "${preOutputStr}" ]] && preOutputStr="USERNAME-ERROR"
		outputStr="${outputStr//"${token_UserName}"/"${preOutputStr}"}"
	fi

	## Hostname
	if ((doAlgo_HostName)); then
		_fMustBeInPath hostname
		preOutputStr=""
		preOutputStr="$(hostname --short 2>/dev/null || true)"
		if [[ -n "${preOutputStr}" ]]; then
			if ((doHash_HostName)); then
				## Cryptographic hash
				preOutputStr="$(echo "${preOutputStr}" | sha256sum | grep -iPo "[0123456789abcdef]+")"  ## existence of sha256sum is already checked in fInit().
				[[ -n "${preOutputStr}" ]] && preOutputStr="${preOutputStr^^}"
				[[ -n "${preOutputStr}" ]] && preOutputStr="$(x9convertbase1 $extCliFlags --ibase 16 ${preOutputStr} $outBase)"
				[[ -n "${preOutputStr}" ]] && [[ $keepOnlyRighmostHashChars_HostName -gt 0 ]] && [[ $keepOnlyRighmostHashChars_HostName -lt ${#preOutputStr} ]] && preOutputStr="${preOutputStr: -$keepOnlyRighmostHashChars_HostName}"
			else :;
				## Do numeric conversion if and when x9convertbase1 supports --ibase of '38hostname'.
				## For now just leave hostname unaltered.
				true
			fi
		fi
		[[ -z "${preOutputStr}" ]] && preOutputStr="HOSTNAME-ERROR"
		outputStr="${outputStr//"${token_HostName}"/"${preOutputStr}"}"
	fi

	## FQDN (Fully-Qualified host & Domain Name); for non-domain hosts, usually the same as hostname.
	if ((doAlgo_FQDN)); then
		_fMustBeInPath hostname
		preOutputStr=""
		preOutputStr="$(hostname --fqdn 2>/dev/null || true)"
		if [[ -n "${preOutputStr}" ]]; then
			if ((doHash_FQDN)); then
				## Cryptographic hash
				preOutputStr="$(echo "${preOutputStr}" | sha256sum | grep -iPo "[0123456789abcdef]+")"  ## existence of sha256sum is already checked in fInit().
				[[ -n "${preOutputStr}" ]] && preOutputStr="${preOutputStr^^}"
				[[ -n "${preOutputStr}" ]] && preOutputStr="$(x9convertbase1 $extCliFlags --ibase 16 ${preOutputStr} $outBase)"
				[[ -n "${preOutputStr}" ]] && [[ $keepOnlyRighmostHashChars_FQDN -gt 0 ]] && [[ $keepOnlyRighmostHashChars_FQDN -lt ${#preOutputStr} ]] && preOutputStr="${preOutputStr: -$keepOnlyRighmostHashChars_FQDN}"
			else :;
				## Do numeric conversion if and when x9convertbase1 supports --ibase of '38hostname'.
				## For now just leave FQDN unaltered.
				true
			fi
		fi
		[[ -z "${preOutputStr}" ]] && preOutputStr="FQDN-ERROR"
		outputStr="${outputStr//"${token_FQDN}"/"${preOutputStr}"}"
	fi

	## Primary MAC address (connected to gateway)
	if ((doAlgo_MAC)); then
		_fMustBeInPath ip
		[[ ! -d "/sys/class/net" ]] && fThrowError  "Looking in '/sys/class/net/*/address' for primary MAC address, but it doesn't seem to exist on this distro."  "${FUNCNAME[0]}"
		preOutputStr=""
		preOutputStr="$(cat "/sys/class/net/$(ip route show default | grep -iPv "dev br" | awk '/default/ {print $5}' | head -n 1)/address" 2>/dev/null || true)"
		preOutputStr="${preOutputStr//":"/""}"
		preOutputStr="${preOutputStr^^}"
		[[ -n "${preOutputStr}" ]] && preOutputStr="$(x9convertbase1 $extCliFlags --ibase 16 ${preOutputStr} $outBase)"
		[[ -z "${preOutputStr}" ]] && preOutputStr="MAC-ERROR"
		outputStr="${outputStr//"${token_MAC}"/"${preOutputStr}"}"
	fi

	## UUID (v4), "GUID" also acceptable
	if ((doAlgo_UUID)); then
		_fMustBeInPath uuid
		preOutputStr=""
		preOutputStr="$(uuid -v 4 -F SIV 2>/dev/null || true)"  ## Output UUID v4 in base 10
		[[ -n "${preOutputStr}" ]] && preOutputStr="$(x9convertbase1 $extCliFlags ${preOutputStr} $outBase)"
		[[ -z "${preOutputStr}" ]] && preOutputStr="UUID-ERROR"
		outputStr="${outputStr//"${token_UUID}"/"${preOutputStr}"}"
	fi

	## Random chars
	if ((doAlgo_Random)); then
		_fMustBeInPath od
		local -i intermediateCharCount=$((randomCharCount*2))  ## 2X is just an arbitrary multiplier to insure there's enough digits after base conversion from 16 to at least 256.
		preOutputStr=""
		preOutputStr="$(od -A n -t x -N ${intermediateCharCount} /dev/urandom 2>/dev/null || true)"
		[[ -n "${preOutputStr}" ]] && preOutputStr="${preOutputStr//[[:space:]]/""}"
		[[ -n "${preOutputStr}" ]] && preOutputStr="${preOutputStr^^}"  ## od outputs hex in lowercase, x9convertbase1 --ibase 16 expects uppercase.
		[[ -n "${preOutputStr}" ]] && preOutputStr="$(x9convertbase1 $extCliFlags --ibase 16 ${preOutputStr} $outBase 2>/dev/null || true)"
		[[ -n "${preOutputStr}" ]] && preOutputStr="${preOutputStr: -$randomCharCount}"
		[[ -z "${preOutputStr}" ]] && preOutputStr="RANDOM-ERROR"
		outputStr="${outputStr//"${token_Random}"/"${preOutputStr}"}"
	fi

	## DateTime
	if ((doAlgo_DateTime)); then

		_fMustBeInPath bc

		## Constants
		local -r fmt_dtMS_HumanReadable="+%Y%m%d%H%M%S.%3N" #....: Eg '20231231235959.999'
		local -r fmt_dtMS_Formatted="+%Y-%m-%d %H:%M:%S.%3N" #...: Eg '2023-12-31 23:59:59.999'
		local -r fmt_dtMS_Ticks="+%s.%3N" #......................: Unix ticks ('epoch'). Integer seconds since 1970, fractional milliseconds.

		## Get precise date to be used for all calcs from here. Everything you need to now about date command:
		##	date --utc --date @1695577254.931 "+%Y-%m-%d %H:%M:%S.%3N"            Ticks to formatted date
		##	date --utc --date "2023-09-21 12:44:18.932" "+%Y-%m-%d %H:%M:%S.%3N"  Convert date formatting
		##	date --utc --date "2023-09-21 12:44:18.932" "+%s.%3N"                 Convert date by string to ticks
		local dateTimeTicksMS=""
		if [[ -n "${dtOverride}" ]]; then
			## Use override date/time
			if [[ "${dtOverride}" == "$(echo "${dtOverride}" | grep -iPo "[0-9\.]+")" ]]; then
				## Override given as ticks
				dateTimeTicksMS="$(date --utc --date @"${dtOverride}" "${fmt_dtMS_Ticks}")"
			else
				## Hope that 'date' will understand the string given
				dateTimeTicksMS="$(date --utc --date "${dtOverride}" "${fmt_dtMS_Ticks}")"
			fi
		else
			## Use current UTC date/time
			dateTimeTicksMS="$(date --utc "${fmt_dtMS_Ticks}")"
		fi
		local -r dateTimeTicksMS="${dateTimeTicksMS}"

		tmpStr=""
		preOutputStr=""

		case $dtAlgo in

			## Base-converts the current UTC unix minutes, seconds, or nanoseconds since 1970-01-01 00:00:00, as appropriate according to $precision_DateTime.
			1)
				tmpStr="${dateTimeTicksMS/"."/""}"  ## Just remove the decimal point, which in this case is the same as multiplying by 1000 (to turn seconds.milliseconds into whole milliseconds).
				if   [[ $precision_DateTime -gt 0 ]]; then  tmpInt=${tmpStr} #................ Millisecond precision
				elif [[ $precision_DateTime -eq 0 ]]; then  tmpInt=$(( tmpStr /  1000 )) #.... Second precision
				else                                        tmpInt=$(( tmpStr / 60000 )) #.... Minute precision
				fi
				[[ $tmpInt -ne 0 ]] && preOutputStr="$(x9convertbase1 $extCliFlags ${tmpInt} $outBase)"
				;;

			## UTC time in YYYYMMDDHHmm[SS[NNN]] is treated as one big integer, then base-converted, as appropriate according to $precision_DateTime.
			2)
				tmpStr="$(date -d @${dateTimeTicksMS} "${fmt_dtMS_HumanReadable}")"  ## Returns date in format 'YYYYmmDDHHMMSSNNN'.
				if [[ $precision_DateTime -gt 0 ]]; then
					## Millisecond precision; already done
					:
				elif [[ $precision_DateTime -eq 0 ]]; then
					## Second precision; strip off last three digits
					tmpStr="${tmpStr:0:-3}"
				else
					## Less precision (no millenium, minute precision)
					tmpStr="${tmpStr:0:-5}"
					fRemoveMillenium_byref "${tmpStr}" tmpStr
				fi
				tmpInt=${tmpStr//"."/""}
				[[ $tmpInt -ne 0 ]] && preOutputStr="$(x9convertbase1 $extCliFlags ${tmpInt} $outBase)"
				;;

			## UTC [YYYY], [MM], [DD], [HH], [mm], [SS], and [NNN] are all treated as seperate fields and base-converted individually, as appropriate according to $precision_DateTime.
			3)
				## fDateAsFields_byref() sets preOutputStr as output from tmpStr input
				local -r zeroInBase="$(x9convertbase1 $extCliFlags 0 $outBase)"  ## This will be needed repeatedly by fDateAsFields_byref(), so save cycles by getting in only once here.
				tmpStr="$(date -d @${dateTimeTicksMS} "${fmt_dtMS_HumanReadable}")"  ## Returns date in format 'YYYYmmDDHHMMSSNNN'.
				if   [[ $precision_DateTime -gt 0 ]]; then  fDateAsFields_byref 1 1 1 1 1 1 1  ## Millisecond precision
				elif [[ $precision_DateTime -eq 0 ]]; then  fDateAsFields_byref 1 1 1 1 1 1 0  ## Second precision
				else                                        fDateAsFields_byref 1 1 1 1 1 0 0  ## Less precision (no millenium, minute precision)
				fi  ;;

			## UTC [YYYY], [MM], and [DD] are treated as seperate fields and base-converted individually.
			## ([HH][mm]), ([HH][mm][SS]), or ([HH][mm][NNN]) as a whole are divided up evenly to maximize the granularity of the entire specified numeric base, as appropriate according to $precision_DateTime.
			4)
				local -r zeroInBase="$(x9convertbase1 $extCliFlags 0 $outBase)"  ## This will be needed repeatedly by fDateAsFields_byref(), so save cycles by getting in only once here.
				local -r formattedDate="$(date -d @${dateTimeTicksMS} "${fmt_dtMS_Formatted}")"  ## Returns date in format 'YYYY-mm-DD HH:MM:SS.NNN'.
				tmpStr="$(date -d @${dateTimeTicksMS} "${fmt_dtMS_HumanReadable}")"  ## Returns date in format 'YYYYmmDDHHMMSSNNN'.

				## First, get [Y]YYYmmDD as separate fields
				fDateAsFields_byref 1 1 1 0 0 0 0 ## This function sets preOutputStr as output from tmpStr input

				## Next, calculate HHMM[SS[NNN]] to desired granularity for specified base

				## Get best hard-coded character count; per base, per precision
				local -i tmpCharCount=0
				if [[ $precision_DateTime -gt 0 ]]; then
					## Approximately millisecond precision
					case $outBaseInt in
						10)  tmpCharCount=8  ;;  ## 0.0009 seconds per tick; +14% [+015%]
						16)  tmpCharCount=7  ;;  ## 0.0003s, +068% (or tmpCharCount=6, 0.0051s, -415%)
						26)  tmpCharCount=6  ;;  ## 0.0003s, +072%
						32)  tmpCharCount=5  ;;  ## 0.0026s, -157%
						36)  tmpCharCount=5  ;;  ## 0.0014s, -043%
						48)  tmpCharCount=5  ;;  ## 0.0003s, +066%
						52)  tmpCharCount=5  ;;  ## 0.0002s, +077%
						62)  tmpCharCount=4  ;;  ## 0.0058s, -485% [-284%]
						64)  tmpCharCount=4  ;;  ## 0.0051s, -415% [-248%]
						128) tmpCharCount=4  ;;  ## 0.0003s, +139% [+068%]
						256) tmpCharCount=3  ;;  ## 0.0051s, -248% [-415%]
					esac
				elif [[ $precision_DateTime -eq 0 ]]; then
					## Approximately second precision
					case $outBaseInt in
						10)  tmpCharCount=5  ;;  ## 0.86 seconds per tick; +14%
						16)  tmpCharCount=4  ;;  ## 1.32s, -032%
						26)  tmpCharCount=3  ;;  ## 4.92s, -392% (or tmpCharCount=4, 0.19s, +81%)
						32)  tmpCharCount=3  ;;  ## 2.64s, -164%
						36)  tmpCharCount=3  ;;  ## 1.85s, -085%
						48)  tmpCharCount=3  ;;  ## 0.78s, +022%
						52)  tmpCharCount=3  ;;  ## 0.61s, +039%
						62)  tmpCharCount=3  ;;  ## 0.36s, +064%  [+120%]
						64)  tmpCharCount=3  ;;  ## 0.33s, +067%  [+135%]
						128) tmpCharCount=2  ;;  ## 5.27s, -427%  [-254%]
						256) tmpCharCount=2  ;;  ## 1.32s, -032%  [-028%]
					esac
				else
					## Approximately minute precision
					case $outBaseInt in
						10)  tmpCharCount=3  ;;  ## 86.4 seconds per tick; -44% accurate compared to 60 seconds [or -37% using more comparable average % change]
						16)  tmpCharCount=3  ;;  ## 21.1s, +065%
						26)  tmpCharCount=3  ;;  ##  4.9s, +092%
						32)  tmpCharCount=2  ;;  ## 84.4s, -041%
						36)  tmpCharCount=2  ;;  ## 66.7s, -011%
						48)  tmpCharCount=2  ;;  ## 37.5s, +038%
						52)  tmpCharCount=2  ;;  ## 31.9s, +047%
						62)  tmpCharCount=2  ;;  ## 22.5s, +063% [+0115%]
						64)  tmpCharCount=2  ;;  ## 21.1s, +065% [+0125%]
						128) tmpCharCount=2  ;;  ##  5.3s, +091% [+0564%]
						256) tmpCharCount=2  ;;  ##  1.3s, +098% [+2274%]
					esac
				fi

				## Get an accurate fraction of the UTC day elapsed so far (in base 10)
				local -r isoDate="${tmpStr:0:4}-${tmpStr:4:2}-${tmpStr:6:2}"
				local -r midnightPrev=$(date --utc --date "${isoDate}"        "${fmt_dtMS_Ticks}")
				local -r midnightNext=$(date --utc --date "${isoDate} +1 day" "${fmt_dtMS_Ticks}")
				local -r nowTicks=$(    date --utc --date "${formattedDate}"  "${fmt_dtMS_Ticks}")
				local -r percentOfDayNowUTC="$(bc -l <<< "(${nowTicks} - ${midnightPrev}) / (${midnightNext} - ${midnightPrev})")"

				## Calculate (in base 10) the possible ticks per day (=[target base]^[char count]); we want an integer, and bc without -l will give us that.
				local -i possibleBaseTicksPerDay=$(bc <<< "${outBaseInt}^${tmpCharCount}")

				## Multiply available ticks times the fraction of day elapsed so far (have to divide as last operation for bc rounding to work)
				local -i baseTicksPassed=$(bc -l <<< "scale=0; ${percentOfDayNowUTC} * ${possibleBaseTicksPerDay} / 1")

				##DEBUG
				#fEchoVarAndVal tmpStr
				#fEchoVarAndVal isoDate
				#fEchoVarAndVal fmt_dtMS_Ticks
				#fEchoVarAndVal midnightPrev
				#fEchoVarAndVal midnightNext
				#fEchoVarAndVal nowTicks
				#fEchoVarAndVal percentOfDayNowUTC
				#fEchoVarAndVal possibleBaseTicksPerDay
				#fEchoVarAndVal baseTicksPassed
				#echo

				## Convert ticks elapsed from base 10 to specified base, and append it to previous conversions
				preOutputStr="${preOutputStr}$(x9convertbase1 $extCliFlags "${baseTicksPassed}" $outBase)"

				;;

		esac
		[[ -z "${preOutputStr}" ]] && preOutputStr="DATETIME-ERROR"
		outputStr="${outputStr//"${token_DateTime}"/"${preOutputStr}"}"
	fi

	echo "${outputStr}"

	## Has to be an 'if', not an '&&' chain - a false chain would become the script's exit code.
	if ((doClipOut)) && [[ -n "$(which xclip 2>/dev/null || true)" ]]; then
		echo -n "${outputStr}" | xclip -selection clipboard || true
	fi

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fInit(){

	## Constants
	local -r _allArgs="$*"

	## Variables for intermediate arg processing, with defaults
	local arg_outFormat="${default_outFormat}"
	local arg_dtOverride=""
	local arg_outBase="${default_outBase}"
	local arg_dtAlgo="${default_dtAlgo}"
	local arg_precision_DateTime="${default_precision_DateTime}"
	local arg_doHash_UserName="${default_doHash_UserName}"
	local arg_doHash_HostName="${default_doHash_HostName}"
	local arg_doHash_FQDN="${default_doHash_FQDN}"
	local arg_keepOnlyRighmostHashChars_UserName="${default_keepOnlyRighmostHashChars_UserName}"
	local arg_keepOnlyRighmostHashChars_HostName="${default_keepOnlyRighmostHashChars_HostName}"
	local arg_keepOnlyRighmostHashChars_FQDN="${default_keepOnlyRighmostHashChars_FQDN}"
	local arg_randomCharCount="${default_randomCharCount}"
	local arg_doLcase="${dofault_doLCaseIfAppropriate}"
	local arg_doClipOut="${default_doClipOut}"

	## Determine if we need to show help
	case " ${_allArgs,,} " in
		*" -h "*|*" --help "*)                 fPrint_Copyright_About_Syntax 1; exit 0 ;;
		*" -v "*|*" --ver "*|*" --version "*)  fPrint_Copyright_About_Syntax  ; exit 0 ;;
	esac

	allArgs=("$@")

	## Init for loop
	local    tmpStr=""
	local    currentArg=""
	local    lastSwitch=""
	local -i expectingSwitchParamForNextArg=0

	## Process arguments
	for currentArg in "${allArgs[@]}"; do

		## Test if an option switch or not
		if [[ ${currentArg,,} =~ ^--[^\ \-]+ ]]; then :;
			## It's an option switch

			## Check if this was supposed to NOT be a switch (eg expecting a parameter after previous switch)
			((${expectingSwitchParamForNextArg})) && fThrowError "Expecting a non-switch argument for '${lastSwitch}', instead got '${currentArg}'."  "${FUNCNAME[0]}"

			## Validate switches, and act on unary switches
			tmpStr="${currentArg,,}"  ## Lower case
			tmpStr="${tmpStr:2}"      ## Strip dashes off
			lastSwitch="${tmpStr}"    ## Remember lastSwitch
			case "${tmpStr}" in

				## Unitary switches (that take no extra params); Comment this test out if this script accepts no such thing.
				#"hash-host"*)        doHash_HostName=1  ;;
				#"hash-fqdn"*)        doHash_FQDN=1      ;;

				## Everything else, expecting a non-switch for next argument
				"format"|"fmt"|*"algo"|"base"|*"prec"*|"random-char-count"|"lc"*|*"case"|"lower"*|"clip"*|"oc"*|"hash"*|"keep-only"*|*"override")
					expectingSwitchParamForNextArg=1 ;;

				"") : ;;  ## Special case of user passing bare "--". Usually means "end of arg processing", but ignore for now.

				## ¯\_(ツ)_/¯
				*)  fThrowError  "Argument invalid or not expected in this context: '${currentArg}'."  "${FUNCNAME[0]}" ;;

			esac

		else
			## It's not an option switch; could be an option switch param, or a positional arg

			if ((expectingSwitchParamForNextArg)); then
				## Expecting option switch param

				case "${lastSwitch,,}" in
					"format"|"fmt")                        arg_outFormat="${currentArg}"                       ;;
					*"override")                           arg_dtOverride="${currentArg}"                      ;;
					"base")                                arg_outBase="${currentArg,,}"                       ;;
					*"algo")                               arg_dtAlgo=$currentArg                              ;;
					*"prec"*)                              arg_precision_DateTime=$currentArg                  ;;
					"hash-user"*)                          arg_doHash_UserName="${currentArg,,}"               ;;
					"hash-host"*)                          arg_doHash_HostName="${currentArg,,}"               ;;
					"hash-fqdn"*)                          arg_doHash_FQDN="${currentArg,,}"                   ;;
					"keep-only-righmost-hash-chars-user"*) arg_keepOnlyRighmostHashChars_UserName=$currentArg  ;;
					"keep-only-righmost-hash-chars-host"*) arg_keepOnlyRighmostHashChars_HostName=$currentArg  ;;
					"keep-only-righmost-hash-chars-fqdn")  arg_keepOnlyRighmostHashChars_FQDN=$currentArg      ;;
					"random-char-count")                   arg_randomCharCount=$currentArg                     ;;
					"lc"*|*"case"|"lower"*)                arg_doLcase="${currentArg,,}"                       ;;
					"clip"*|"oc"*)                         arg_doClipOut="${currentArg,,}"                     ;;
					*)                                     fThrowError "Unkown parameters. Switch: '--${lastSwitch}', current parameter: '${currentArg}'."  "${FUNCNAME[0]}" ;;
				esac
				expectingSwitchParamForNextArg=0

			else
				## Well it must be a positional arg then.

				fThrowError "Unexpected positional argument: '${currentArg}'."  "${FUNCNAME[0]}"

			fi

		fi
	done

	## Validate; post-loop
	((expectingSwitchParamForNextArg)) && fThrowError "Never received a parameter for switch '--${lastSwitch}'."

	## Variables not validated here
	dtOverride="${arg_dtOverride}"

	## Validate and normalize base
	fNormalizeBaseName_byRef                                                       "${arg_outBase}"                             outBase
	outBaseInt=$(echo "${outBase}" | grep -iPo "[0-9]+" | head -n 1)

	## Transform and validation
	[[ -n "${arg_dtAlgo}"                              ]] && fNormalizeInt_byRef   "${arg_dtAlgo}"                              dtAlgo                               1    4  "--dtalgo"
	[[ -n "${arg_precision_DateTime}"                  ]] && fNormalizeInt_byRef   "${arg_precision_DateTime}"                  precision_DateTime                  -1    1  "--precision"
	[[ -n "${arg_keepOnlyRighmostHashChars_UserName}"  ]] && fNormalizeInt_byRef   "${arg_keepOnlyRighmostHashChars_UserName}"  keepOnlyRighmostHashChars_UserName   0  256  "--keep-only-righmost-hash-chars-username"
	[[ -n "${arg_keepOnlyRighmostHashChars_HostName}"  ]] && fNormalizeInt_byRef   "${arg_keepOnlyRighmostHashChars_HostName}"  keepOnlyRighmostHashChars_HostName   0  256  "--keep-only-righmost-hash-chars-hostname"
	[[ -n "${arg_keepOnlyRighmostHashChars_FQDN}"      ]] && fNormalizeInt_byRef   "${arg_keepOnlyRighmostHashChars_FQDN}"      keepOnlyRighmostHashChars_FQDN       0  256  "--keep-only-righmost-hash-chars-fqdn"
	[[ -n "${arg_randomCharCount}"                     ]] && fNormalizeInt_byRef   "${arg_randomCharCount}"                     randomCharCount                      0  256  "--random-char-count"
	[[ -n "${arg_doHash_UserName}"                     ]] && fNormalizeBool_byRef  "${arg_doHash_UserName}"                     doHash_UserName                              "--hash-username"
	[[ -n "${arg_doHash_HostName}"                     ]] && fNormalizeBool_byRef  "${arg_doHash_HostName}"                     doHash_HostName                              "--hash-hostname"
	[[ -n "${arg_doHash_FQDN}"                         ]] && fNormalizeBool_byRef  "${arg_doHash_FQDN}"                         doHash_FQDN                                  "--hash-fqdn"
	[[ -n "${arg_doLcase}"                             ]] && fNormalizeBool_byRef  "${arg_doLcase}"                             doLCaseIfAppropriate                         "--lcase"
	[[ -n "${arg_doClipOut}"                           ]] && fNormalizeBool_byRef  "${arg_doClipOut}"                           doClipOut                                    "--clipout"

	## Replace user-friendly variables, with tokens that are unlikely to ever be used in either user output or numeric base, so that the same letters that will show up in bases won't screw up the search-and-replace process during fMain() processing.
	outFormat="${arg_outFormat}"
	outFormat="${outFormat//"%datetime"/"${token_DateTime}"}"
	outFormat="${outFormat//"%dt"/"${token_DateTime}"}"
	outFormat="${outFormat//"%da"/"${token_DateTime}"}"
	outFormat="${outFormat//"%d"/"${token_DateTime}"}"
	outFormat="${outFormat//"%uuid"/"${token_UUID}"}"  ## Process uuid/guid before username, so that the last thing checked can be %u for username
	outFormat="${outFormat//"%uu"/"${token_UUID}"}"
	outFormat="${outFormat//"%guid"/"${token_UUID}"}"
	outFormat="${outFormat//"%g"/"${token_UUID}"}"
	outFormat="${outFormat//"%username"/"${token_UserName}"}"
	outFormat="${outFormat//"%user"/"${token_UserName}"}"
	outFormat="${outFormat//"%usr"/"${token_UserName}"}"
	outFormat="${outFormat//"%un"/"${token_UserName}"}"
	outFormat="${outFormat//"%us"/"${token_UserName}"}"
	outFormat="${outFormat//"%u"/"${token_UserName}"}"
	outFormat="${outFormat//"%hostname"/"${token_HostName}"}"
	outFormat="${outFormat//"%host"/"${token_HostName}"}"
	outFormat="${outFormat//"%hn"/"${token_HostName}"}"
	outFormat="${outFormat//"%h"/"${token_HostName}"}"
	outFormat="${outFormat//"%fqdn"/"${token_FQDN}"}"
	outFormat="${outFormat//"%f"/"${token_FQDN}"}"
	outFormat="${outFormat//"%macaddress"/"${token_MAC}"}"
	outFormat="${outFormat//"%macaddr"/"${token_MAC}"}"
	outFormat="${outFormat//"%mac"/"${token_MAC}"}"
	outFormat="${outFormat//"%ma"/"${token_MAC}"}"
	outFormat="${outFormat//"%m"/"${token_MAC}"}"
	outFormat="${outFormat//"%random"/"${token_Random}"}"
	outFormat="${outFormat//"%rand"/"${token_Random}"}"
	outFormat="${outFormat//"%rnd"/"${token_Random}"}"
	outFormat="${outFormat//"%r"/"${token_Random}"}"

	## Determine what algos to include (these need to be checked multiple times, and we don't want to do string scanning every time that happens).
	local -i tmpMatchIndex=0
	fFindStrIndex_byref  "${outFormat}"  "${token_DateTime}"  tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_DateTime=1
	fFindStrIndex_byref  "${outFormat}"  "${token_UserName}"  tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_UserName=1
	fFindStrIndex_byref  "${outFormat}"  "${token_HostName}"  tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_HostName=1
	fFindStrIndex_byref  "${outFormat}"  "${token_FQDN}"      tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_FQDN=1
	fFindStrIndex_byref  "${outFormat}"  "${token_MAC}"       tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_MAC=1
	fFindStrIndex_byref  "${outFormat}"  "${token_UUID}"      tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_UUID=1
	fFindStrIndex_byref  "${outFormat}"  "${token_Random}"    tmpMatchIndex; [[ $tmpMatchIndex -gt 0 ]] && doAlgo_Random=1

	## At least one algo must be specified
	if [[ "${doAlgo_DateTime}${doAlgo_HostName}${doAlgo_FQDN}${doAlgo_MAC}${doAlgo_Random}${doAlgo_UUID}${doAlgo_UserName}" == "0000000" ]]; then
		fThrowError  "No algorithm was specified or allowed to by default; there's nothing to do."  "${FUNCNAME[0]}"
	fi

	## Misc validation
	((doAlgo_Random)) && [[ $randomCharCount -le 0 ]] && fThrowError  "You apparently want to include random characters, but specified '--random-char-count' of <=0."  "${FUNCNAME[0]}"
	if ((doHash_UserName)) || ((doHash_HostName)) || ((doHash_FQDN)); then _fMustBeInPath sha256sum; fi

#	## Validate lowercase flag, change a value of 'true' to 'false' if it's not valid in context.
#	## This is too much brainwork to impose on the user, so just do the work here and don't complain about a contextually 'invalid' flag value.
#	## x9convertbase1 should inherit this bit of benevolence in the future. [Done!]
#	if ((doLCaseIfAppropriate)); then
#		case ${outBase} in
#			10|32w|48j1|52|62|64|64r|64u|64j1u|64j1uw|128|128j1|256j1)
#				## Can't do lcase; either it doesn't make sense (eg base 10), or it would result in data loss for mixed-case bases, and a validation error by x9convertbase1.
#				doLCaseIfAppropriate=0
#				;;
#			16|26|32|32c|32h|32r|36)
#				## These are OK to switch to lower case, so leave set to true.
#				: ;;
#		esac
#	fi

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fDateAsFields_byref(){
	##	Uses caller's variables:
	##		$tmpStr as input value
	##		$preOutputStr as output variable to set

	## Args
	local -ri doConvertYYYY=$1
	local -ri doConvertMo=$2
	local -ri doConvertDD=$3
	local -ri doConvertHH=$4
	local -ri doConvertMi=$5
	local -ri doConvertSS=$6
	local -ri doConvertNNN=$7

	## Variables
	local wrkStr=""

	## Init
	preOutputStr=""

	if ((doConvertYYYY)); then
	## Possilby remove millenium and convert [Y]YYY
		wrkStr="${tmpStr:0:4}"
		[[ $precision_DateTime -lt 0 ]] && fRemoveMillenium_byref "${wrkStr}" wrkStr
		preOutputStr="${preOutputStr}$(x9convertbase1 $extCliFlags "${wrkStr}" $outBase)"
	#	preOutputStr="${preOutputStr}Y-$(x9convertbase1 $extCliFlags "${wrkStr}" $outBase)"
	fi

	#fEchoVarAndVal preOutputStr
	#fEchoVarAndVal extCliFlags

	if ((doConvertMo)); then
		## Convert and pad month, mm
		wrkStr="${tmpStr:4:2}"
		wrkStr="$(x9convertbase1 $extCliFlags "${wrkStr}" "${outBase}")"
		fZeroPadValInBase_byref "${wrkStr}" 12 $outBaseInt "${zeroInBase}" wrkStr  ## The magic #12 is the number of months per year, the max val for mm
		preOutputStr="${preOutputStr}${wrkStr}"
	#	preOutputStr="${preOutputStr} m-${wrkStr}"
	fi

	if ((doConvertDD)); then
		## Convert and pad day, DD
		wrkStr="${tmpStr:6:2}"
		wrkStr="$(x9convertbase1 $extCliFlags "${wrkStr}" "${outBase}")"
		fZeroPadValInBase_byref "${wrkStr}" 31 $outBaseInt "${zeroInBase}" wrkStr  ## The magic #31 is the max number of days in a month, the max val for DD
		preOutputStr="${preOutputStr}${wrkStr}"
	#	preOutputStr="${preOutputStr} D-${wrkStr}"
	fi

	if ((doConvertHH)); then
		## Convert and pad 24h, HH
		wrkStr="${tmpStr:8:2}"
		wrkStr="$(x9convertbase1 $extCliFlags "${wrkStr}" "${outBase}")"
		fZeroPadValInBase_byref "${wrkStr}" 23 $outBaseInt "${zeroInBase}" wrkStr  ## The magic #23 is the max val HH can get.
		preOutputStr="${preOutputStr}${wrkStr}"
	#	preOutputStr="${preOutputStr} H-${wrkStr}"
	fi

	if ((doConvertMi)); then
		## Convert and pad minutes, MM
		wrkStr="${tmpStr:10:2}"
		wrkStr="$(x9convertbase1 $extCliFlags "${wrkStr}" "${outBase}")"
		fZeroPadValInBase_byref "${wrkStr}" 59 $outBaseInt "${zeroInBase}" wrkStr  ## The magic #59 is the max val MM can get.
		preOutputStr="${preOutputStr}${wrkStr}"
	#	preOutputStr="${preOutputStr} M-${wrkStr}"
	fi

	if ((doConvertSS)); then
		## Convert and pad seconds, SS
		wrkStr="${tmpStr:12:2}"
		wrkStr="$(x9convertbase1 $extCliFlags "${wrkStr}" "${outBase}")"
		fZeroPadValInBase_byref "${wrkStr}" 59 $outBaseInt "${zeroInBase}" wrkStr  ## The magic #59 is the max val SS can get.
		preOutputStr="${preOutputStr}${wrkStr}"
	#	preOutputStr="${preOutputStr} S-${wrkStr}"
	fi

	if ((doConvertNNN)); then
		## Convert and pad milliseconds, NNN
		wrkStr="${tmpStr:15:3}"
		wrkStr="$(x9convertbase1 $extCliFlags "${wrkStr}" "${outBase}")"
		fZeroPadValInBase_byref "${wrkStr}" 999 $outBaseInt "${zeroInBase}" wrkStr  ## The magic #999 is the max val NNN can get.
		preOutputStr="${preOutputStr}${wrkStr}"
	#	preOutputStr="${preOutputStr} N-${wrkStr}"
	fi

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fZeroPadValInBase_byref(){
	##	Purpose: Pads a value with leading zeros, up to the max chars required for specified max value in specified base.

	## Args
	local -r  inputVal="$1"    ## The value which may or may not need zero-padding (already in desired base).
	local -r  maxVal="$2"      ## The maximum value that could exist in the caller's context, in base 10.
	local -ri baseInt=$3       ## The numeric base, integer-only (we don't actually care what the symbols are, except for what represents 0).
	local -r  zeroChar="$4"    ## The character that represents zero in the contextual base.
	local -r  retVarName="$5"  ## The caller's variable to populate with the result.

	## Variables
	local retVal=""
	local maxChars=""
	local -i inputCharCount=${#inputVal}
	local -i zerosToPad=0

	## Figure out the max # chars for $maxVal in $baseInt.
	## It's equal to the exponent "x" in ($baseInt^x) + someY = $inputVal, and it doesn't really matter in this context what 'someY' is because it doesn't change the x we're looking for, so we'll discard it ]
	## So then we can simplify to: $baseInt^x = $inputVal. Then solving for x:
	## log[$baseInt]($baseInt^x) = log[$baseInt] * ($inputVal)
	## x * log[$baseInt]($baseInt) = log[$baseInt]($inputVal)
	## x = log[$baseInt]($inputVal)
	## Note that bc can only compute natural logarithm (base e), so this basic math identity becomes useful:
	##	log desiredBase (x) = log base e (x) / log base e (desiredBase)
	##	Translated to bc: bc -l l(x)/l(desiredBase)
	maxChars=$(bc -l <<< "(l($maxVal)/l($baseInt))+1")  ## (log(inputval)/log(base))
	maxChars="${maxChars%.*}"  ## Truncate to integer
	[[ -z "${maxChars}" ]] && maxChars=1  ## Special case
	local -ir maxChars=$maxChars  ## Convert to read-only integer

	## Zero-pad output with base's zero character
	retVal="${inputVal}"
	zerosToPad=$((maxChars-inputCharCount))
	if ((zerosToPad > 0)); then
		for ((i=1; i<=zerosToPad ; i++)); do retVal="${zeroChar}${retVal}"; done
	fi

	eval "${retVarName}='${retVal}'"

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fRemoveMillenium_byref(){
	##	Purpose: Removes the millenium from a date that starts with millenium, eg 20230615 becomes 230615.

	## Args
	local     valStr="$1"
	local -r  varName="$2"  ## The variable to set with modified value.

	valStr="${valStr:1}" #.....................................: Remove first digit
	valStr="$(echo "${valStr}" | grep -iPo "[1-9][0-9]+")" #...: Remove any/all leading 0s, bash won't convert to int with leading 0s

	eval "${varName}='${valStr}'"

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fFindStrIndex_byref() {

	local -r mainStr="$1"
	local -r findStr="$2"
	local -r indexIntVarName="$3"
	local -i retVal=0
	local    testStr=""

	testStr="${mainStr%%"$findStr"*}"
	if [[ "${testStr}" != "${mainStr}" ]]; then
		retVal=${#testStr}
		retVal=$((retVal+1))
	fi

	## Return
	eval "${indexIntVarName}=${retVal}"

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fNormalizeBaseName_byRef(){
	local -r inVal="$1"
	local -r outVarName="$2"
	local    outVal="${inVal}"

	## Base names to numbers
	case "${outVal,,}" in
		"bin"*) outVal="2"  ;;
		"oct"*) outVal="8"  ;;
		"dec"*) outVal="10" ;;
		"hex"*) outVal="16" ;;
	esac

	## Strip "b" or "base" off
	if   [[ -n "$(echo "${outVal}"  | grep -iP "base[0-9]+.*")" ]]; then outVal="${outVal/"base"/""}"
	elif [[ -n "$(echo "${outVal}"  | grep -iP "b[0-9]+.*")"    ]]; then outVal="${outVal/"b"/""}"; fi

	## Validate. Anchored, or a base merely *containing* a valid one (eg '1000', '32x') gets through,
	## and x9convertbase1 then returns empty with rc=0, which surfaces much later as a *-ERROR field.
	if [[ "${outVal}" =~ ^(10|16|26|32|32c|32h|32r|32w|36|48j1|52|62|64|64r|64u|64j1u|64j1uw|128|128j1|256|256j1)$ ]]; then :
	else fThrowError "Unexpected base specified for '--base', '${inVal}'."  "${FUNCNAME[0]}"; fi

	## Return
	eval "${outVarName}='${outVal}'"

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fNormalizeBool_byRef(){
	local -r inVal="$1"
	local -r outIntVarName="$2"
	local -r flagName="$3" #..... For FYI in error message
	local -i outVal=0

	case "${inVal,,}" in
		"1"|"true"|"y"|"yes")  outVal=1  ;;
		"0"|"false"|"n"|"no")  outVal=0  ;;
		*)                     fThrowError "Invalid boolean input for '${flagName}', '${inVal}'."  "${FUNCNAME[0]}" ;;
	esac

	## Return
	eval "${outIntVarName}=${outVal}"

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
fNormalizeInt_byRef(){

	local -r  inVal="$1"
	local -r  outIntVarName="$2"
	local -ri minVal=$3
	local -ri maxVal=$4
	local -r  flagName="$5" #..... For FYI in error message
	local -i  outVal=0

	## Validate
	[[ -z "$(echo "${inVal}" | grep -iPo "[0-9]+" || true)"                          ]] && fThrowError "Invalid integer input for '${flagName}', '${inVal}'."  "${FUNCNAME[0]}"
	[[ "${inVal}" != "$(echo "${inVal}" | grep -iPo "[\-0-9]+" | head -n 1 || true)" ]] && fThrowError "Invalid integer input for '${flagName}', '${inVal}'."  "${FUNCNAME[0]}"

	outVal=$inVal

	if [[ $minVal -lt $maxVal ]]; then
		[[ $outVal -lt $minVal ]] || [[ $outVal -gt $maxVal ]] && fThrowError "Integer for '${flagName}' must be between ${minVal} and ${maxVal}. Passed: ${inVal}."  "${FUNCNAME[0]}"
	fi

	## Return
	eval "${outIntVarName}=${outVal}"

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
function _fMustBeInPath(){

	local -r programToCheckForInPath="$1"
	if [[ -z "${programToCheckForInPath}" ]]; then
		fThrowError "_fMustBeInPath(): Not program specified."
	elif [[ -z "$(command -v "${programToCheckForInPath}" 2>/dev/null || true)" ]]; then
		fThrowError "Not found in path: ${programToCheckForInPath}"
	fi

}


#•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
function fPrint_Copyright_About_Syntax(){

	## Constants
#	local -r additionalLineOfText="$*"

	fPrint_Copyright
	fPrint_AboutAndSyntax
	if [[ "$1" == "1" ]]; then fPrint_Help; fi  ## An '&&' here would return 1 and trip the ERR trap.
#	if [[ -n "${additionalLineOfText}" ]]; then fEcho_Clean "Error: ${additionalLineOfText}"; fi

}


##
##	Generic echo-related stuff.
##	History:
##		- 20190911 JC: Created (mostly by copying TEMPLATE_v*)
##

declare -i _wasLastEchoBlank=0
function fEcho_Clean(){
#	if [[ -n "$1" ]]; then echo -e "$*" | fold -s -w $(tput cols)  ## Break on words, rather than arbitrarily.
	if [[ -n "$1" ]]; then
		echo -e "$*"
		_wasLastEchoBlank=0
	elif [[ $_wasLastEchoBlank -eq 0 ]] && echo; then
		_wasLastEchoBlank=1
	fi
}
# shellcheck disable=2120  ## References arguments, but none are ever passed; Just because this library function isn't called here, doesn't mean it never will in other scripts.
function fEcho()                   { if [[ -n "$*" ]]; then fEcho_Clean "[ $* ]"; else fEcho_Clean ""; fi; }
function fEcho_Force()             { fEcho_ResetBlankCounter; fEcho "$*";                                  }
function fEcho_Clean_Force()       { fEcho_ResetBlankCounter; fEcho_Clean "$*";                            }
function fEchoVarAndVal()          { fEcho_Clean "${2}${1} = '${!1}'";                                     }
function fEcho_ResetBlankCounter() { _wasLastEchoBlank=0;                                                  }


##
##	Generic error-handling  stuff.
##	History
##		- 20190826 JC: Created by copying from 0_library_v2.
##		- 20190919 JC: Slight tweaks to improve newline output.
##

declare -i _wasCleanupRun=0

function fThrowError(){
	local    errMsg="$1"
	local -r funcName="$2"
	[[ -z "${errMsg}" ]] && errMsg="An error occurred."
	if [[ -z "${funcName}" ]]; then
		errMsg="${meName}: ${errMsg}"
	else
		errMsg="${meName}.${funcName}(): ${errMsg}"
	fi
	fEcho_Clean
	fEcho_Clean "${errMsg}"
	fEcho_Clean
	exit 1
}

function _fTrap_Exit(){
	if [[ "${_wasCleanupRun}" == "0" ]]; then  ## String compare is less to fail than integer
		_wasCleanupRun=1
		_fSingleExitPoint "${@}"
	fi
}

function _fTrap_Error(){
	if [[ "${_wasCleanupRun}" == "0" ]]; then  ## String compare is less to fail than integer
		_wasCleanupRun=1
		fEcho_ResetBlankCounter
		_fSingleExitPoint "${@}"
	fi
}

function _fSingleExitPoint(){
	local -r signal="$1";  shift || true
	local -r lineNum="$1"; shift || true
	local -r errNum="$1";  shift || true
	local -r errMsg="$*"
	if [[ "${signal}" == "INT" ]]; then
		fEcho_Force
		fEcho "User interrupted."
		exit 1
	elif [[ "${errNum}" != "0" ]] && [[ "${errNum}" != "1" ]]; then  ## Clunky string compare is less likely to fail than integer
		fEcho_Clean
		fEcho_Clean "Signal .....: '${signal}'"
		fEcho_Clean "Err# .......: '${errNum}'"
		fEcho_Clean "Error ......: '${errMsg}'"
		fEcho_Clean "At line# ...: '${lineNum}'"
		fEcho_Clean
	fi
}

function fDefineTrap_Error_Fatal(){
	true
	trap '_fTrap_Error ERR     ${LINENO} $? $_' ERR
	set -e
}


##
## Execution entry point (do not modify)
##

## Define error and exit handling
set -e; set -E
fDefineTrap_Error_Fatal
trap '_fTrap_Error SIGHUP  ${LINENO} $? $_' SIGHUP
trap '_fTrap_Error SIGINT  ${LINENO} $? $_' SIGINT    ## CTRL+C
trap '_fTrap_Error SIGTERM ${LINENO} $? $_' SIGTERM
trap '_fTrap_Exit  EXIT    ${LINENO} $? $_' EXIT
trap '_fTrap_Exit  INT     ${LINENO} $? $_' INT
trap '_fTrap_Exit  TERM    ${LINENO} $? $_' TERM

declare    meName="$(basename "${BASH_SOURCE[0]}")"


fMain "${@}"


##	Notes on various possible encoding schemes to shrink the number of characters required to store YYYYMMDD-HHMMSS:
##		YYYMM:
##			- YYYYMMDD ............. 29991231 → b62  = 21q5X, 5 digits
##			- YYYYMMDD ............. 29991231 → b32c = WK89Z, 5 digits
##			- YYYYMM ............... 299912   → b62  =  1G1I, 4 digits
##			- YYYY ................. 2999     → b32c =   2XQ, 3 digits
##		*	- YYYY ................. 2999     → b62  =    mN, 2 digits until year 3843
##			- Year as 3-digits .....  999     → b32c =    Z7, 2 digits
##			- Year as 3-digits .....  999     → b62  =    G7, 2 digits
##			- YYYMM ................  99912   → b32c =  31J8, 4 digits
##			- YYYMM ................  99912   → b62  =   PzU, 3 digits
##			- Month up to max ......     12   → b32c =     C, 1 digits
##			- Month up to max ......     12   → b62  =     C, 1 digits
##			- Day up to max ........       31 → b32c =     Z, 1 digit
##			- Day up to max ........       31 → b62  =     V, 1 digit
##		HHMMSS:
##			- HHMMSS .............. 235959 → b32c = 76DQ, 4 digits
##			- HHMMSS .............. 235959 → b62  = zNn,  3 digits
##				or
##			- HH .................. 23     → b32c =    Q, 1 digit
##			- HH .................. 23     → b62  =    N, 1 digit
##			- MMSS ................   5959 → b32c  = 5T7, 3 digits
##			- MM ..................   59   → b32c  =  1V, 2 digits
##			- MM ..................   59   → b62  =    x, 1 digit
##			- SS ..................     59 → b62  =    x, 1 digit
##			= ........................................... 3 digits
##		Base32c:
##			- YYYYMMDDHHMMSS ...............: V8VGAY9VQ   9  Millenium and second accurate
##			-  YYYMMDDHHMMSS ...............: 92S1WKSVQ   9  Century and second
##			-  YYYMMDDHHMMS ................:  X2G61ZCB   8  Century and ten-second
##			- [YYYY][MM][DD][HH][MM][SS] ...:  2XQCZNQQ   8  Millenium and second, separate digits for each unit of time
##			- [ YYY][MM][DD][HH][MM][SS] ...:   Z7CZNQQ   7  Century and second, separate digits for each unit of time
##			- [ YYY][MM][DD][HHMMSS] .......:  Z7CZ76DQ   8 Century and second
##		Base62:
##			- YYYYMMDDHHMMSS ...............: 8W0lprLr    8  Millenium and second, 8 chars until year ~21,000
##			-  YYYMMDDHHMMSS ...............: 2ptsK3iZ    8  Century and second
##			-  YYYMMDDHHMMS ................:  HaaQnyF    7  Century and ten-second
##			- [YYYY][MM][DD][HH][MM][SS] ...:  mNCVNxx    7  Millenium and second, separate digits for each unit of time
##			- [ YYY][MM][DD][HH][MM][SS] ...:  G7CVNxx    7  Century and second, separate digits for each unit of time
##			- [ YYY][MM][DD][HHMMSS] .......:  G7CVzNn    7  Century and second accurate
##		Base62 [YYY*] and various evenly divided divisions:
##			- [YYY][YMMDDHHMMSS_4] .........:  G7zzzz     6  Centuryaccurate, year evenly divided into 2.134-second intervals
##			- [2YYY][MMDDHHMMSS_3] .........:   mNzzz     5  Century accurate, month evenly divided into 11.2-second intervals
##		*	- [2YYY][MM][DD][HHMMSS_2] .....:  mNCVzz     6  Century accurate, day evenly divided into 22.48-second intervals
##		Seconds since 1970 (unix time): 1694050834  $(date +%s)
##			x9convertbase1 --clipout $(date --utc +%s) 32c
##			x9convertbase1 --clipout $(date --utc -d "Jan 1 2024" +%s)
##			- Base32c ......................: 1JFJAGJ     7 digits until year 3058
##			- Base48j1 .....................:  6∮6‡[j     6
##		*	- Base62 .......................:  1qe40Y     6 digits until 3769
##			- Base64j1u ....................:  1a▴IeI     6 digits until 4147
##			- Base64j1uw ...................:  1p▴m2F     6
##			- Base128jc1 ...................:   6t△🜗N     5
##		Seconds since 2000: 747335729
##			x9convertbase1 --clipout $(( $(date +%s) - $(date -d "Jan 1 2000" +%s) )) 32c
##			x9convertbase1 --clipout $(( $(date -d "Jan 1 2500" +%s) - $(date -d "Jan 1 2000" +%s) )) 32c
##			- Base32c ......................:  P8PW1H      6 digits until 2034, 7 digits until 3059
##			- Base62 .......................:   oZkA5      5 digits until 2029, 6 digits until 3799
##		Minutes since 2000: 12455595
##			x9convertbase1 --clipout $(( ($(date -d "Jan 1 2200" +%s) - $(date -d "Jan 1 2000" +%s)) / 60 )) 32c
##			- Base32c ......................:   BW3NB      5 digits until 2063, 6 digits until 4041
##			- Base62 .......................:    qGGh      4 digits until 2028, 5 digits until 3741
